import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-10 ml-10`}
      >
        <nav>
          <ul>
            <li>
              <Link href="/todos">Todos</Link>
            </li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
              <li>
              <Link href="/products">Products</Link>
            </li>
          </ul>
        </nav>
        <hr/>
        {children}
      </body>
    </html>
  );
}
